---
abstract: 'ChromeLogger for Perl'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.13.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Web-ChromeLogger
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Web::ChromeLogger:
    file: lib/Web/ChromeLogger.pm
    version: '0.01'
requires:
  perl: '5.008005'
resources:
  bugtracker: https://github.com/tokuhirom/Web-ChromeLogger/issues
  homepage: https://github.com/tokuhirom/Web-ChromeLogger
  repository: git://github.com/tokuhirom/Web-ChromeLogger.git
version: '0.01'
